name: Notify Discord

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      discord_api_url:
        description: "API URL to notify Discord"
        required: false
        default: "https://discord-notify-bot-jw61.onrender.com"

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discorda
        run: |
          curl -X POST ${{ inputs.discord_api_url }}/send \
          -H "Content-Type: application/json" \
          -d '{
            "status": "${{ job.status }}",
            "message": "Build ${{ job.status }} for commit ${{ github.sha }}",
          }'
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: "1352904828556283955"
          DISCORD_THREAD_ID: "1353306988607438931"